# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ראש פיתוח
email: guytepper@gmail.com
description: בלוג על נושאים שונים הקשורים בפיתוח אינטרנט.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devhead.co.il" # the base hostname & protocol for your site
twitter_username: guytepper
github_username:  guytepper

# Build settings
exclude: [node_modules, gulpfile.js, package.json]
markdown: kramdown
permalink: /:slug
lang: he
